// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SongAPI.DbContexts;

#nullable disable

namespace SongAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230529202029_newUisidField")]
    partial class newUisidField
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SongAPI.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistId"), 1L, 1);

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UISId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ArtistId");

                    b.HasIndex("UISId");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            ArtistId = 1,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682269480/Artists/02-the-weeknd-press-2019-cr-Nabil-Elderkin-billboard-1548_fycfoa.jpg",
                            Name = "The Weeknd",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 2,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682269732/Artists/ab67706c0000da84c3e6fe76812ed7962f227ef5_cubxpd.jpg",
                            Name = "Taylor Swift",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 3,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682269761/Artists/ab6761610000e5eb9e690225ad4445530612ccc9_xlkvve.jpg",
                            Name = "Ed Sheeran",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 4,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682269803/Artists/ab67616d00001e0258039b5147731b6e52202e46_uykiyz.jpg",
                            Name = "Miley Cyrus",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 5,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682269822/Artists/93e6b100a00437a05f57aa66ce41208811296fc8_kdrzvk.jpg",
                            Name = "Shakira",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 6,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682269842/Artists/1fc2f537d678d701d7d143a8fd4f0c2f29fbde22_din0jd.jpg",
                            Name = "Rihanna",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 7,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682269870/Artists/ab6761610000e5ebcdce7620dc940db079bf4952_gnaodu.jpg",
                            Name = "Ariana Grande",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 8,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682269892/Artists/ab6761610000e5eb8ae7f2aaa9817a704a87ea36_t0xtiu.jpg",
                            Name = "Justin Bieber",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 9,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682269912/Artists/ab6761610000e5eb4293385d324db8558179afd9_n2wmlf.jpg",
                            Name = "Drake",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 10,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682269931/Artists/ab6761610000e5eb75348e1aade2645ad9c58829_zwniut.jpg",
                            Name = "David Guetta",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 11,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682269967/Artists/ab6761610000e5eb7eb7f6371aad8e67e01f0a03_uzxwhw.jpg",
                            Name = "SZA",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 12,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270017/Artists/ab6761610000e5eba00b11c129b27a88fc72f36b_jcnhb6.jpg",
                            Name = "Eminem",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 13,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270038/Artists/ab6761610000e5ebf7db7c8ede90a019c54590bb_uxyhzo.jpg",
                            Name = "Harry Styles",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 14,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270059/Artists/bad-bunny-spotify-record-1669829243_jtdn0r.jpg",
                            Name = "Bad Bunny",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 15,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270078/Artists/ab6761610000e5eb578905d5539cff25568dc097_xe3tuo.jpg",
                            Name = "Calvin Harris",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 16,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270096/Artists/ab6761610000e5eb989ed05e1f0570cc4726c2d3_abwerh.jpg",
                            Name = "Coldplay",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 17,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270113/Artists/ab6761610000e5ebd42a27db3286b58553da8858_otae5z.jpg",
                            Name = "Dua Lipa",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 18,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270132/Artists/ab67616d00001e02005cd7d0ae87b081601f6cca_uv6bz2.jpg",
                            Name = "Sam Smith",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 19,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270152/Artists/ab6761610000e5eb920dc1f617550de8388f368e_wngyms.jpg",
                            Name = "Imagine Dragons",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 20,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270170/Artists/cfd6e47fbe4446750ec209dfa37bc919cb55c86f_ywdkov.jpg",
                            Name = "21 Savage",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 21,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270197/Artists/ab6761610000e5ebc36dd9eb55fb0db4911f25dd_uwbq2j.jpg",
                            Name = "Bruno Mars",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 22,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270217/Artists/ab6761610000e5eba5205abffd84341e5bace828_a0bncr.jpg",
                            Name = "Selena Gomez",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 23,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270233/Artists/ab6761610000e5eb288ac05481cedc5bddb5b11b_zuuqjw.jpg",
                            Name = "Maroon 5",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 24,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270258/Artists/ab67616d00001e028093238ec0c71ef7c95c8fb1_pdh9d2.jpg",
                            Name = "Lady Gaga",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 25,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270278/Artists/ab67616d00001e024c65275edad3ab7ddb4ed230_hus4k6.jpg",
                            Name = "Post Malone",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 26,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270293/Artists/ab6761610000e5eb41e4a3b8c1d45a9e49b6de21_phywup.jpg",
                            Name = "Marshmello",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 27,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270309/Artists/ab6761610000e5eb6a0594d5bff11a7e0c7ceb1a_ce87cr.jpg",
                            Name = "Karol G",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 28,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270331/Artists/ab67616d0000b273fd61ea11e50ba0b7eade9466_tq2ae4.jpg",
                            Name = "Kanye West",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 29,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270354/Artists/Metro-Boomin_olzkw9.jpg",
                            Name = "Metro Boomin",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 30,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270386/Artists/ab67616d00001e02c42f6b7b41537a5fae06840a_o2m9g9.jpg",
                            Name = "Doja Cat",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 31,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270401/Artists/ab6761610000e5ebd8b9980db67272cb4d2c3daf_nr6ito.jpg",
                            Name = "Billie Eilish",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 32,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270420/Artists/ab6761610000e5ebdc9dcb7e4a97b4552e1224d6_foxi3d.jpg",
                            Name = "Katy Perry",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 33,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270437/Artists/ab6761610000e5eb31072db9da0311ecfabe96bf_ovmdnj.jpg",
                            Name = "Khalid",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 34,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270454/Artists/ab6761610000e5eb923e85a0eefbab49fd8d4920_tlxd4i.jpg",
                            Name = "Rauw Alejandro",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 35,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270477/Artists/ab67616d00001e02922a7339d969b5f0262580f5_nfwpzv.jpg",
                            Name = "J Balvin",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 36,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270493/Artists/ab6761610000e5eb68f6e5892075d7f22615bd17_musdvc.jpg",
                            Name = "Adele",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 37,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270508/Artists/ab6761610000e5ebe50aa80e0f5869f84f6874d1_u4vvar.jpg",
                            Name = "Chris Brown",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 38,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270539/Artists/Daddy-Yankee-MSG-July-2016-Billboard-1548_kzutuz.jpg",
                            Name = "Daddy Yankee",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 39,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270553/Artists/ab6761610000e5eb12e3f20d05a8d6cfde988715_rylfhj.jpg",
                            Name = "Beyoncé",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 41,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270581/Artists/2a832cd2b8dd5d0deef6d682ca52ea29f5dda859_igzpo8.jpg",
                            Name = "Nicki Minaj",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 42,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270598/Artists/ab6761610000e5eb77bf00f67e21f514dc44c485_xon2ed.jpg",
                            Name = "OneRepublic",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 43,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270614/Artists/ab67616d0000b273e0b64c8be3c4e804abcb2696_bwmsno.jpg",
                            Name = "Future",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 44,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270630/Artists/ab6761610000e5eb39ce949d62ff47fc1de1a2d9_pxtyqg.jpg",
                            Name = "Ozuna",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 46,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270658/Artists/ab6761610000e5ebe707b87e3f65997f6c09bfff_h6ynqo.jpg",
                            Name = "Travis Scott",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 47,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270677/Artists/af2b8e57f6d7b5d43a616bd1e27ba552cd8bfd42_pojktd.jpg",
                            Name = "Queen",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 48,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270700/Artists/ab67616d00001e028f072024e0358fc5c62eba41_x6euf6.jpg",
                            Name = "Rosalía",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 49,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270715/Artists/ab67616d00001e025d199c9f6e6562aafa5aa357_byexkr.jpg",
                            Name = "Sia",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 50,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270728/Artists/ab6761610000e5ebc692afc666512dc946a7358f_r3muiq.jpg",
                            Name = "Bebe Rexha",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 51,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270743/Artists/ab6761610000e5ebf0c20db5ef6c6fbe5135d2e4_qjm8hw.jpg",
                            Name = "XXXTENTACION",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 52,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270760/Artists/ab6761610000e5ebeb63bf6379a9ea8453a30020_tpxgs3.jpg",
                            Name = "Don Toliver",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 53,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270773/Artists/ab6761610000e5eb876faa285687786c3d314ae0_orb6p0.jpg",
                            Name = "Kid Cudi",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 54,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270798/Artists/ab67616d0000b273c1968cb5cd60558e0ca42b4b_ophtti.jpg",
                            Name = "Giveon",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 55,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270815/Artists/ab67706c0000da8465b1230626a7c2f4506f149b_qvqdo9.jpg",
                            Name = "Dave",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 56,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270833/Artists/mhevc5ptefhzny9zqw8a_do5tpq.jpg",
                            Name = "Baby Keem",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 57,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270848/Artists/ab6761610000e5ebbd5d3e1b363c3e26710661c3_kzniic.jpg",
                            Name = "Tory Lanez",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 58,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270864/Artists/ab67616d00001e02a1e8b73748ee972a4c22be16_lzl0jz.jpg",
                            Name = "Stormzy",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 59,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270879/Artists/ab6761610000e5eb803f228472451496cb2f5b88_osynjw.jpg",
                            Name = "Gunna",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 60,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270894/Artists/ab6761610000e5eb437b9e2a82505b3d93ff1022_zleojo.jpg",
                            Name = "Kendrick Lamar",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 61,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270909/Artists/ab6761610000e5eb8278b782cbb5a3963db88ada_x94wcf.jpg",
                            Name = "Tyler, The Creator",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 62,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270925/Artists/ab6761610000e5ebb99cacf8acd5378206767261_wrbjz4.jpg",
                            Name = "Lana Del Rey",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 63,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270942/Artists/ab6761610000e5eb4ddb58b186bace4ed7e9f26e_d8tdui.jpg",
                            Name = "Kali Uchis",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 64,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270966/Artists/ab67616d00001e02617c314e94693fad9a26f798_r2gpty.jpg",
                            Name = "Daniel Caesar",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 65,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270981/Artists/ab6761610000e5ebf8e7a2d1a01fd98e43ee57dc_odotcz.jpg",
                            Name = "6LACK",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 66,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682270995/Artists/ab6761610000e5ebee452efcf24aa4124fb28d94_un9ioe.jpg",
                            Name = "A$AP Rocky",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ArtistId = 67,
                            ImageUrl = "https://res.cloudinary.com/ddd8z6szf/image/upload/v1682271027/Artists/ab67616d0000b27323c552a7a4fdafac02e08c34_wyepjs.jpg",
                            Name = "Joji",
                            UISId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("SongAPI.Models.Collaboration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("CanAddSongs")
                        .HasColumnType("bit");

                    b.Property<bool>("CanRemoveSongs")
                        .HasColumnType("bit");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("UserId");

                    b.ToTable("Collaborations");
                });

            modelBuilder.Entity("SongAPI.Models.Feature", b =>
                {
                    b.Property<int>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeatureId"), 1L, 1);

                    b.Property<int>("ArtistID")
                        .HasColumnType("int");

                    b.Property<int>("FeatureRole")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("FeatureId");

                    b.HasIndex("ArtistID");

                    b.HasIndex("SongId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("SongAPI.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Description = "Acoustic music is a genre that emphasizes the use of acoustic instruments and natural sound, without the use of electronic or electric instruments. It often features a stripped-down, raw sound that highlights the musicality of the performers.",
                            Name = "Acoustic"
                        },
                        new
                        {
                            GenreId = 2,
                            Description = "Afrobeat is a music genre that originated in West Africa, characterized by a fusion of African rhythms and funk and jazz influences. It features complex percussion patterns, brass instrumentation, and call-and-response vocals.",
                            Name = "Afrobeat"
                        },
                        new
                        {
                            GenreId = 3,
                            Description = "Alternative music is a broad term that refers to any music that is not mainstream or commercially popular. It encompasses a wide range of styles and genres, from indie rock and post-punk to electronic and experimental music.",
                            Name = "Alternative"
                        },
                        new
                        {
                            GenreId = 4,
                            Description = "Ambient music is a genre that focuses on creating a mood or atmosphere through soundscapes and textures, often without a traditional melody or rhythm. It is often used in film and TV soundtracks and for relaxation or meditation purposes.",
                            Name = "Ambient"
                        },
                        new
                        {
                            GenreId = 5,
                            Description = "Anime music refers to the soundtracks and theme songs from Japanese animated TV shows and movies. It often features pop and rock influences, as well as orchestral and electronic elements.",
                            Name = "Anime"
                        },
                        new
                        {
                            GenreId = 6,
                            Description = "Blues is a genre of music that originated in African American communities in the United States in the late 19th century. It features a distinctive 12-bar chord progression, call-and-response vocals, and often deals with themes of heartache, loss, and injustice.",
                            Name = "Blues"
                        },
                        new
                        {
                            GenreId = 7,
                            Description = "Bossa nova is a genre of Brazilian music that originated in the late 1950s. It is characterized by its soft, lilting rhythms, gentle melodies, and often features the use of acoustic guitar and piano.",
                            Name = "BossaNova"
                        },
                        new
                        {
                            GenreId = 8,
                            Description = "Breakbeat is a genre of electronic music that originated in the mid-1980s. It is characterized by its heavy use of breaks, which are sampled from other songs and looped. Breakbeat is often used in the context of DJ sets and dance parties, and it is known for its high energy and fast-paced rhythms.",
                            Name = "Breakbeat"
                        },
                        new
                        {
                            GenreId = 9,
                            Description = "Children's music is music that is specifically targeted at children. It includes nursery rhymes, lullabies, and educational songs, among other types of music. Children's music is often designed to be educational and entertaining, and it is an important part of many children's lives.",
                            Name = "Children"
                        },
                        new
                        {
                            GenreId = 10,
                            Description = "Chill music, also known as chillout, is a genre of electronic music that is characterized by its relaxed and mellow sound. It often features slow tempos, atmospheric textures, and ambient soundscapes. Chill music is often used for relaxation, meditation, and background music.",
                            Name = "Chill"
                        },
                        new
                        {
                            GenreId = 11,
                            Description = "Classical music is a genre of music that originated in Europe in the late 18th century. It is characterized by its use of orchestral instruments, complex compositions, and formal structure. Classical music has had a significant impact on music throughout the centuries, and many iconic composers are considered to be among the greatest artists of all time.",
                            Name = "Classical"
                        },
                        new
                        {
                            GenreId = 12,
                            Description = "Club music is a genre of electronic dance music that is specifically designed for clubs and dance parties. It is characterized by its high energy and fast-paced rhythms, and it often incorporates elements of other genres such as techno, house, and trance. Club music is meant to be danced to, and it is popular in clubs around the world.",
                            Name = "Club"
                        },
                        new
                        {
                            GenreId = 13,
                            Description = "Comedy music is a genre of music that is designed to be humorous. It can include parodies, satirical songs, and humorous skits. Some well-known comedy musicians include Weird Al Yankovic and Flight of the Conchords.",
                            Name = "Comedy"
                        },
                        new
                        {
                            GenreId = 14,
                            Description = "Classical music is a genre of music that originated in Europe around the mid-18th century. It is characterized by its formal structure, complex harmonies, and use of instruments such as the violin, piano, and cello. Famous classical composers include Mozart, Beethoven, and Bach.",
                            Name = "Classical"
                        },
                        new
                        {
                            GenreId = 15,
                            Description = "Country music is a genre of music that originated in the southern United States in the early 20th century. It is characterized by its use of stringed instruments such as the guitar and fiddle, as well as its themes of love, heartbreak, and rural life. Famous country musicians include Johnny Cash, Dolly Parton, and Garth Brooks.",
                            Name = "Country"
                        },
                        new
                        {
                            GenreId = 16,
                            Description = "Dance music is a genre of popular music that is designed for dancing. It is characterized by its repetitive beats and synthesized sounds. Popular dance music genres include disco, house, and techno.",
                            Name = "Dance"
                        },
                        new
                        {
                            GenreId = 17,
                            Description = "Deep house is a subgenre of house music that originated in the 1980s. It is characterized by its use of synthesizers, drum machines, and a slower tempo than other house music genres. Deep house is often associated with a more laid-back and relaxed atmosphere than other electronic dance music genres.",
                            Name = "Deep House"
                        },
                        new
                        {
                            GenreId = 18,
                            Description = "Disco is a genre of dance music that emerged in the 1970s and 1980s. It features a repetitive 4/4 beat and synthesized melodies and is known for its association with disco balls, colorful lights, and dancing.",
                            Name = "Disco"
                        },
                        new
                        {
                            GenreId = 19,
                            Description = "Disney music refers to the soundtracks and songs featured in Disney movies and TV shows. It covers a wide range of genres, including pop, rock, musical theater, and orchestral music.",
                            Name = "Disney"
                        },
                        new
                        {
                            GenreId = 20,
                            Description = "Drum and Bass is a subgenre of electronic music that emerged in the 1990s. It is characterized by fast breakbeats and heavy basslines, often with a dark or aggressive tone.",
                            Name = "Drum and Bass"
                        },
                        new
                        {
                            GenreId = 21,
                            Description = "Dub is a genre of reggae that emerged in the 1960s. It features remixes of existing songs with emphasis on the drums and bass and the use of effects such as echo and reverb.",
                            Name = "Dub"
                        },
                        new
                        {
                            GenreId = 22,
                            Description = "Dubstep is a genre of electronic dance music that emerged in the early 2000s. It features a syncopated rhythm and heavy basslines, often with a dark or aggressive tone.",
                            Name = "Dubstep"
                        },
                        new
                        {
                            GenreId = 23,
                            Description = "EDM, short for Electronic Dance Music, is an umbrella term for various genres of electronic music designed for dance-based entertainment, such as house, techno, trance, and dubstep.",
                            Name = "EDM"
                        },
                        new
                        {
                            GenreId = 24,
                            Description = "Electro is a genre of electronic dance music that emerged in the 1980s. It features a distinctive robotic sound, often achieved through the use of synthesizers and vocoders.",
                            Name = "Electro"
                        },
                        new
                        {
                            GenreId = 25,
                            Description = "Electronic music is a broad category of music that encompasses a wide range of electronic-based sounds, including synthpop, techno, house, and ambient.",
                            Name = "Electronic"
                        },
                        new
                        {
                            GenreId = 26,
                            Description = "Emo is a subgenre of punk rock that emerged in the 1990s. It features introspective and emotionally-charged lyrics, often dealing with topics such as heartbreak and self-doubt.",
                            Name = "Emo"
                        },
                        new
                        {
                            GenreId = 27,
                            Description = "Folk music is a genre that encompasses a wide range of traditional and contemporary music styles. It features acoustic instruments such as guitar, banjo, and fiddle, and often tells stories or conveys social messages.",
                            Name = "Folk"
                        },
                        new
                        {
                            GenreId = 28,
                            Description = "Funk is a music genre that originated in African American communities in the mid-1960s when musicians created a rhythmic, danceable new form of music through a mixture of soul, jazz, and R&B. Funk emphasizes the bassline and rhythm section and often features extended solos and complex, syncopated rhythms. Some of the most well-known funk artists include James Brown, Parliament-Funkadelic, Sly and the Family Stone, and Prince.",
                            Name = "Funk"
                        },
                        new
                        {
                            GenreId = 29,
                            Description = "Groove is a music genre that originated in the 1970s and is characterized by its infectious, danceable rhythms and funky basslines. It has its roots in funk and soul music and has influenced many other genres, including hip hop, R&B, and electronic music. Some of the most well-known groove artists include Earth, Wind & Fire, Kool & the Gang, and Prince.",
                            Name = "Groove"
                        },
                        new
                        {
                            GenreId = 30,
                            Description = "Guitar music refers to any genre of music that prominently features the guitar. The guitar is a versatile instrument and is used in a wide variety of genres, from classical music to heavy metal. Guitar music is often characterized by its use of intricate melodies and complex chord progressions.",
                            Name = "Guitar"
                        },
                        new
                        {
                            GenreId = 31,
                            Description = "Happy music is any genre of music that is uplifting, cheerful, and positive in tone. It is often characterized by its upbeat tempo and catchy melodies. Happy music is often used in commercials, movies, and other media to evoke a positive emotional response from the listener.",
                            Name = "Happy"
                        },
                        new
                        {
                            GenreId = 32,
                            Description = "Hard rock is a subgenre of rock music that originated in the 1960s and is characterized by its heavy, amplified sound, distorted guitar riffs, and aggressive lyrics. Some of the most famous hard rock bands include AC/DC, Guns N' Roses, and Led Zeppelin.",
                            Name = "Hard Rock"
                        },
                        new
                        {
                            GenreId = 33,
                            Description = "Heavy metal is a genre of rock music that originated in the late 1960s and is characterized by its heavy, distorted guitars, fast tempo, and aggressive lyrics. Heavy metal is often associated with themes of power, rebellion, and anti-authority.",
                            Name = "Heavy Metal"
                        },
                        new
                        {
                            GenreId = 34,
                            Description = "Hip hop is a genre of music that originated in African American and Latinx communities in the United States in the 1970s. It is characterized by its use of rapping, DJing, and sampling, and often features politically and socially conscious lyrics. Hip hop has become one of the most popular genres of music in the world.",
                            Name = "Hip Hop"
                        },
                        new
                        {
                            GenreId = 35,
                            Description = "Holiday music is any genre of music that is associated with a particular holiday or time of year. Examples include Christmas music, Hanukkah music, and Halloween music. Holiday music is often played in stores and on the radio during the holiday season.",
                            Name = "Holidays"
                        },
                        new
                        {
                            GenreId = 36,
                            Description = "House music is a genre of electronic dance music that originated in Chicago in the early 1980s. It is characterized by its repetitive 4/4 beat and synthesized melodies, often accompanied by samples or vocals. House music has since become a global phenomenon and has spawned many sub-genres.",
                            Name = "House"
                        },
                        new
                        {
                            GenreId = 37,
                            Description = "Intelligent dance music (IDM) is a genre of electronic music that emerged in the early 1990s. It is characterized by complex rhythms, intricate melodies, and experimental sound design, often incorporating elements of ambient, techno, and breakbeat. IDM is often associated with artists on the Warp Records label, such as Aphex Twin and Autechre.",
                            Name = "IDM"
                        },
                        new
                        {
                            GenreId = 38,
                            Description = "Indie music is a genre of alternative rock that emerged in the 1980s. It is characterized by its DIY ethos and rejection of mainstream culture, often featuring lo-fi production values and introspective lyrics. Indie music has since expanded to include many sub-genres, such as indie pop and indie folk.",
                            Name = "Indie"
                        },
                        new
                        {
                            GenreId = 39,
                            Description = "Industrial music is a genre of experimental music that emerged in the 1970s. It is characterized by its use of harsh, abrasive sounds, often created through the use of metal percussion and heavily distorted guitar and synth tones. Industrial music has since expanded to include many sub-genres, such as power electronics and rhythmic noise.",
                            Name = "Industrial"
                        },
                        new
                        {
                            GenreId = 40,
                            Description = "Jazz is a genre of music that originated in African American communities during the late 19th and early 20th century. It is characterized by improvisation, syncopated rhythms, and the use of varied harmonic progressions.",
                            Name = "Jazz"
                        },
                        new
                        {
                            GenreId = 41,
                            Description = "K-Pop is a genre of popular music originating in South Korea. It is characterized by a wide variety of audiovisual elements, including colorful visuals, elaborate choreography, and a wide range of musical styles.",
                            Name = "K-Pop"
                        },
                        new
                        {
                            GenreId = 42,
                            Description = "Kids music is specifically targeted to children, with simple lyrics, catchy melodies, and themes related to childhood experiences and learning.",
                            Name = "Kids"
                        },
                        new
                        {
                            GenreId = 43,
                            Description = "Latin music encompasses a wide range of styles and genres from Latin America, including salsa, merengue, bachata, reggaeton, and more. It is characterized by vibrant rhythms, passionate vocals, and rich cultural influences.",
                            Name = "Latin"
                        },
                        new
                        {
                            GenreId = 44,
                            Description = "Metal is a genre of rock music that emerged in the late 1960s and early 1970s. It is characterized by its heavy, distorted guitar sound, thunderous basslines, and powerful vocals.",
                            Name = "Metal"
                        },
                        new
                        {
                            GenreId = 45,
                            Description = "Movie soundtracks are collections of music composed specifically for films. They often feature orchestral arrangements, vocal performances, and songs that are used to help convey the emotional tone and mood of the film.",
                            Name = "Movies"
                        },
                        new
                        {
                            GenreId = 46,
                            Description = "A form of theater in which music has a leading role and the parts are taken by singers, typically in costumes and with minimal sets.",
                            Name = "Opera"
                        },
                        new
                        {
                            GenreId = 47,
                            Description = "A genre of music that is typically upbeat and played at parties or celebrations.",
                            Name = "Party"
                        },
                        new
                        {
                            GenreId = 48,
                            Description = "A genre of music that features the piano as the primary instrument.",
                            Name = "Piano"
                        },
                        new
                        {
                            GenreId = 49,
                            Description = "A genre of popular music that originated in the 1950s and is characterized by catchy melodies and a strong rhythmic beat.",
                            Name = "Pop"
                        },
                        new
                        {
                            GenreId = 50,
                            Description = "A genre of rock music that emerged in the mid-1970s and is characterized by fast, hard-edged music and often politically charged lyrics.",
                            Name = "Punk"
                        },
                        new
                        {
                            GenreId = 51,
                            Description = "A genre of popular African-American music that originated in the 1940s and is characterized by a strong rhythm and blues influence.",
                            Name = "R&B"
                        },
                        new
                        {
                            GenreId = 52,
                            Description = "A genre of music that is relaxing and suitable for a rainy day.",
                            Name = "Rainy Day"
                        },
                        new
                        {
                            GenreId = 53,
                            Description = "Reggae is a music genre that originated in Jamaica in the late 1960s. It is characterized by its off-beat rhythms, prominent basslines, and use of Jamaican Patois.",
                            Name = "Reggae"
                        },
                        new
                        {
                            GenreId = 54,
                            Description = "Reggaeton is a music genre that originated in Puerto Rico in the early 1990s. It blends elements of reggae, hip-hop, and Latin American music styles such as salsa and merengue.",
                            Name = "Reggaeton"
                        },
                        new
                        {
                            GenreId = 55,
                            Description = "Road Trip music is a genre of music that is often associated with driving, adventure and travel. It typically features upbeat and catchy songs that are perfect for long car rides or exploring new destinations.",
                            Name = "Road Trip"
                        },
                        new
                        {
                            GenreId = 56,
                            Description = "Rock music is a genre of popular music that originated as 'rock and roll' in the United States in the 1950s, and developed into a range of different styles in the 1960s and later.",
                            Name = "Rock"
                        },
                        new
                        {
                            GenreId = 57,
                            Description = "Rock 'n' roll is a genre of popular music that originated in the United States in the 1950s. It is characterized by its heavy use of electric guitars, bass guitar, and drums, and often features simple, catchy melodies and lyrics about teenage life and romance.",
                            Name = "Rock 'n' Roll"
                        },
                        new
                        {
                            GenreId = 58,
                            Description = "Romance music is a genre of music that is often associated with love, passion, and sensuality. It typically features slow, melodic songs with romantic lyrics and lush orchestration.",
                            Name = "Romance"
                        },
                        new
                        {
                            GenreId = 59,
                            Description = "Sad music is a genre of music that is often associated with sadness, heartbreak, and emotional pain. It typically features slow, melancholic songs with sad lyrics and sparse instrumentation.",
                            Name = "Sad"
                        },
                        new
                        {
                            GenreId = 60,
                            Description = "Salsa is a music genre that originated in Cuba in the 1920s and 1930s. It is characterized by its lively, upbeat rhythms, use of brass instruments, and prominent percussion section.",
                            Name = "Salsa"
                        },
                        new
                        {
                            GenreId = 61,
                            Description = "Samba is a music genre that originated in Brazil in the early 20th century. It is characterized by its fast, syncopated rhythms, use of percussion instruments, and lively, upbeat melodies.",
                            Name = "Samba"
                        },
                        new
                        {
                            GenreId = 62,
                            Description = "Sleep music is a genre of music that is designed to promote relaxation and help listeners fall asleep. This type of music typically features slow, calming melodies and minimal instrumentation, and may include sounds such as white noise or nature sounds.",
                            Name = "Sleep"
                        },
                        new
                        {
                            GenreId = 63,
                            Description = "Soul is a genre of music that originated in the United States in the 1950s and 1960s. It is characterized by its strong vocal performances and emphasis on rhythm and blues. Soul music often features a strong backbeat and horn section.",
                            Name = "Soul"
                        },
                        new
                        {
                            GenreId = 64,
                            Description = "Soundtracks refer to the music that is featured in movies, TV shows, and video games. This music is often specifically composed for the production, and can include a wide variety of styles and genres.",
                            Name = "Soundtracks"
                        },
                        new
                        {
                            GenreId = 65,
                            Description = "Study music is a genre of music that is designed to help students focus and concentrate while studying or working. This type of music typically features instrumental arrangements with minimal lyrics and a calming, repetitive melody.",
                            Name = "Study"
                        },
                        new
                        {
                            GenreId = 66,
                            Description = "Summer music is a genre of music that is associated with warm weather, outdoor activities, and relaxation. This type of music often features upbeat, tropical rhythms and lyrics that celebrate the joys of summer.",
                            Name = "Summer"
                        },
                        new
                        {
                            GenreId = 67,
                            Description = "Tango is a musical genre and dance that originated in the working-class port neighborhoods of Buenos Aires and Montevideo in the late 19th century, with influences from Italian, Spanish, and African music.",
                            Name = "Tango"
                        },
                        new
                        {
                            GenreId = 68,
                            Description = "Techno is a genre of electronic dance music that emerged in Detroit, Michigan, in the United States during the mid-to-late 1980s.",
                            Name = "Techno"
                        },
                        new
                        {
                            GenreId = 69,
                            Description = "Trance is a genre of electronic dance music that developed in the 1990s, characterized by a tempo of between 125 and 150 beats per minute, repetitive melodic phrases, and a musical form that builds up and breaks down throughout a track.",
                            Name = "Trance"
                        },
                        new
                        {
                            GenreId = 70,
                            Description = "Workout music is a genre of music that is specifically designed to be played during exercise or fitness routines, often featuring upbeat tempos and motivating lyrics to encourage physical activity.",
                            Name = "Workout"
                        },
                        new
                        {
                            GenreId = 71,
                            Description = "World music is a genre of music that encompasses traditional music from various cultures around the world, as well as contemporary fusion and crossover styles that incorporate elements of traditional music from different regions.",
                            Name = "World Music"
                        });
                });

            modelBuilder.Entity("SongAPI.Models.GenreSong", b =>
                {
                    b.Property<int>("SongGenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SongGenreId"), 1L, 1);

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("SongGenreId");

                    b.HasIndex("GenreId");

                    b.HasIndex("SongId");

                    b.ToTable("GenreSong");
                });

            modelBuilder.Entity("SongAPI.Models.Playlist", b =>
                {
                    b.Property<Guid>("PlaylitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Tittle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlaylitId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("SongAPI.Models.PlaylistLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("LikeDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("UserId");

                    b.ToTable("PlaylistsLike");
                });

            modelBuilder.Entity("SongAPI.Models.PlaylistSong", b =>
                {
                    b.Property<int>("PlaySongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaySongId"), 1L, 1);

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("PlaySongId");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("SongId");

                    b.ToTable("PlaylistsSong");
                });

            modelBuilder.Entity("SongAPI.Models.Release", b =>
                {
                    b.Property<int>("ReleaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReleaseId"), 1L, 1);

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReleaseType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReleaseId");

                    b.HasIndex("ArtistId");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("SongAPI.Models.Song", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SongId"), 1L, 1);

                    b.Property<bool>("HasFeatures")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsExplicite")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("Length")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReleaseId")
                        .HasColumnType("int");

                    b.HasKey("SongId");

                    b.HasIndex("ReleaseId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("SongAPI.Models.SongLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("LikeDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.HasIndex("UserId");

                    b.ToTable("SongsLike");
                });

            modelBuilder.Entity("SongAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<Guid>("UISId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("UISId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SongAPI.Models.Collaboration", b =>
                {
                    b.HasOne("SongAPI.Models.Playlist", "Playlist")
                        .WithMany("Collaborations")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SongAPI.Models.User", "User")
                        .WithMany("Collaborations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SongAPI.Models.Feature", b =>
                {
                    b.HasOne("SongAPI.Models.Artist", "Artist")
                        .WithMany("Features")
                        .HasForeignKey("ArtistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SongAPI.Models.Song", "Song")
                        .WithMany("Features")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("SongAPI.Models.GenreSong", b =>
                {
                    b.HasOne("SongAPI.Models.Genre", "Genre")
                        .WithMany("Songs")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SongAPI.Models.Song", "Song")
                        .WithMany("Genres")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("SongAPI.Models.PlaylistLike", b =>
                {
                    b.HasOne("SongAPI.Models.Playlist", "Playlist")
                        .WithMany("PlaylistLikes")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SongAPI.Models.User", "User")
                        .WithMany("PlaylistLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SongAPI.Models.PlaylistSong", b =>
                {
                    b.HasOne("SongAPI.Models.Playlist", "Playlist")
                        .WithMany("Songs")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SongAPI.Models.Song", "Song")
                        .WithMany("Playlists")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("SongAPI.Models.Release", b =>
                {
                    b.HasOne("SongAPI.Models.Artist", "Artist")
                        .WithMany("Releases")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("SongAPI.Models.Song", b =>
                {
                    b.HasOne("SongAPI.Models.Release", "Release")
                        .WithMany("Songs")
                        .HasForeignKey("ReleaseId");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("SongAPI.Models.SongLike", b =>
                {
                    b.HasOne("SongAPI.Models.Song", "Song")
                        .WithMany("SongLikes")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SongAPI.Models.User", "User")
                        .WithMany("SongLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SongAPI.Models.Artist", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Releases");
                });

            modelBuilder.Entity("SongAPI.Models.Genre", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("SongAPI.Models.Playlist", b =>
                {
                    b.Navigation("Collaborations");

                    b.Navigation("PlaylistLikes");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("SongAPI.Models.Release", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("SongAPI.Models.Song", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Genres");

                    b.Navigation("Playlists");

                    b.Navigation("SongLikes");
                });

            modelBuilder.Entity("SongAPI.Models.User", b =>
                {
                    b.Navigation("Collaborations");

                    b.Navigation("PlaylistLikes");

                    b.Navigation("SongLikes");
                });
#pragma warning restore 612, 618
        }
    }
}
